service: spa-backend

frameworkVersion: '2'

# 全体向けの共通設定
provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  profile: '' # credentials
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::GetAtt: [ExampleTable, Arn]
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# 独自定義値を設定
custom:
  defaultStage: dev

# Lambda設定(APIGatewayも自動生成)
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer

# CloudFormationテンプレート設定
resources:
  - ${file(./conf/dynamodb.yml)}
  - ${file(./conf/cognito.yml)}
  - ${file(./conf/apigateway-authorizer.yml)}
  - ${file(./conf/bucket.yml)}
